[package]
name = "rust-volunteerer"
version = "0.9.0"
edition = "2021"

authors = ["Khang Dinh"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"

[[bin]]
name = "rust-volunteerer"
path = "main.rs"
